# Generated by Django 2.2.13 on 2020-09-09 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_auto_20200909_0816'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.Purchase')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Sub_topic')),
            ],
        ),
    ]
