# Generated by Django 2.2.13 on 2020-09-09 07:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumComments',
            new_name='Forum_comments',
        ),
        migrations.RenameModel(
            old_name='ForumTopic',
            new_name='Forum_topic',
        ),
    ]
