# Generated by Django 2.2.13 on 2020-09-09 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20200909_0759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum_comments',
            new_name='Forum_comment',
        ),
    ]
