# Generated by Django 2.2.13 on 2020-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200909_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_comment',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
