# Generated by Django 2.2.13 on 2020-09-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
