# Generated by Django 2.2.13 on 2020-09-09 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20200909_0816'),
        ('purchases', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
        migrations.RenameModel(
            old_name='Subtopics',
            new_name='Sub_topic',
        ),
    ]
