# Generated by Django 2.2.13 on 2020-09-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20200909_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
