# Generated by Django 2.2.13 on 2020-09-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20200928_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='intro',
            new_name='introduction',
        ),
    ]
