# Generated by Django 2.2.13 on 2020-09-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20200930_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
