# Generated by Django 2.2.13 on 2020-10-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20201001_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_topic',
            old_name='vid',
            new_name='video',
        ),
    ]
